inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
AllCops:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/{rails,rake}"
    - !ruby/regexp /old_and_unused\.rb$/
  TargetRubyVersion: 2.6
